[package]
name = "dao_mint"
version = "0.1.0"
description = "The vault containing real funds to control the FridgeDAO."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "dao_mint"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []
custom-heap = []
custom-panic = []


[dependencies]
anchor-lang = "0.32.1"
anchor-spl = "0.32.1"
fridge_dao = { version = "0.1.0", path = "../fridge_dao", features = ["cpi"] }


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
